spring:
  config:
    import: optional:file:../.env[.properties]
  docker:
    compose:
      lifecycle-management: start_only
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3307/abms}
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
  sql:
    init:
      mode: always
  ai:
    openai:
      api-key: ${AI_OPENAI_API_KEY}

app:
  auth:
    registration-mail:
      from: ${APP_AUTH_REGISTRATION_MAIL_FROM:no-reply@iabacus.co.kr}
      subject: ${APP_AUTH_REGISTRATION_MAIL_SUBJECT:[ABMS] 회원가입 링크 안내}
      confirm-url: ${APP_AUTH_REGISTRATION_MAIL_CONFIRM_URL:http://localhost:5173/auths/registration-confirm}

logging:
  level:
    p6spy: debug
