spring:
  application:
    name: abms
  jpa:
    hibernate:
      ddl-auto: create
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true

  ai:
    google:
      genai:
        api-key: ${AI_GOOGLE_GENAI_API_KEY}

logging:
  level:
    p6spy: debug
