spring:
  application:
    name: abms
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  docker:
    compose:
      lifecycle-management: start_only
  threads:
    virtual:
      enabled: true

  ai:
    vertex:
      ai:
        gemini:
          project-id: nsales-pro
          location: us-central1
          model: gemini-2.0-flash-lite
  config:
    import: optional:file:.env[.properties]

logging:
  level:
    p6spy: debug
